### ISSUE TITLE
Changes to CreateTasksTerminatedException

### ISSUE THREAD

**Issue by jasper-schneider** [Azure/azure-batch-sdk-for-java#3]
Some issues and changes to consider for the CreateTasksTerminatedException class:
- The pendingList parameter is not used in the constructor.
- The constructor should probably take readonly copies of the list
- Consider renaming the class to CreateTasksErrorException or something similar?
- Consider renaming the properties and parameters to either failedTasks and pendingTasks or failureList and pendingList.  Currently, failureTasks and pendingList aren't aligned with each other.

**Comment by xingwu1** [comment]
Resolved.
