### ISSUE TITLE
Bulk add task uses first instance of BatchClientParallelOptions

### ISSUE THREAD

**Issue by jasper-schneider** [Azure/azure-batch-sdk-for-java#4]
The bulk add task operation uses the first instance of the BatchClientParallelOptions in the behaviors list:

https://github.com/Azure/azure-batch-sdk-for-java/blob/master/src/main/java/com/microsoft/azure/batch/TaskOperations.java#L199

        for (BatchClientBehavior op : bhMgr.getMasterListOfBehaviors()) {
            if (op instanceof BatchClientParallelOptions) {
                threadNumber = ((BatchClientParallelOptions)op).maxDegreeOfParallelism();
                break;
            }
        }

Typically, the behaviors are processed in order, and the last interceptor to modify a property is the winner.  This is advertised in our docs.  Using the first instance of the parallel options is inconsistent.

**Comment by xingwu1** [comment]
Resolved.
